#import "../fragments/Users.gql"

query users($currentPage: Int, $perPage: Int, $search: String) {
  users(currentPage: $currentPage, perPage: $perPage, search: $search) {
    total
    users {
      _id
      name {
        first
        last
      }
      emailAddress
      oAuthProvider
    }
  }
}

query user($_id: String) {
  user(_id: $_id) {
    ...UserAttributes
  }
}
