subscription commentAdded($documentId: String!) {
  commentAdded(documentId: $documentId) {
    _id
    documentId
    comment
    createdAt
    user {
      _id
      name {
        first
        last
      }
    }
  }
}
